include:
  - board: nice_nano_v2
    shield: duplicis        # Usa el directorio base con duplicis.dtsi
    config: duplicis_left.conf   # Selecciona la configuración para la mitad izquierda
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: duplicis        # Usa el mismo directorio base
    config: duplicis_right.conf  # Selecciona la configuración para la mitad derecha
